apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend-web
  template:
    metadata:
      labels:
        component: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000